# Generated by Django 4.2.4 on 2023-08-28 14:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("garagem", "0008_veiculo_acessorio_alter_veiculo_modelo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="veiculo",
            options={"verbose_name": "Veículos"},
        ),
    ]
