# Generated by Django 4.2.4 on 2023-08-29 15:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("garagem", "0011_remove_veiculo_imagem_veiculo_imagem"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="veiculo",
            options={"verbose_name": "Veículo"},
        ),
    ]
